name: GitHub Actions Demo
on: [push]
jobs:

  UnitsTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install pytest
      - run: pytest 

  BuildDockerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t prod_lce .